packages:
  - "apps/*"
  - "packages/*"
  - "products/we-are-family/apps/*"
  - "legacy-system/apps/*"
  - "legacy-system/contracts"
allowBuilds:
  esbuild: set this to true or false
onlyBuiltDependencies:
  - esbuild
