packages:
  - "apps/*"
  - "packages/*"
  - "products/we-are-family/apps/*"
  - "products/famili-principal/apps/*"
  - "legacy-system/apps/*"
  - "legacy-system/contracts"
allowBuilds:
  esbuild: true
onlyBuiltDependencies:
  - esbuild
